### ISSUE TITLE
Fix Typo in README.md

### ISSUE THREAD

**Issue by AkshayHere** [CuriousGrids/FirstTimers#40]
Command to check Git version has typo in README.md has typo.

Change `git --vesrion` to `git --version`

**Comment by AkhileshThite** [comment]
> Command to check Git version has typo in README.md has typo.
> 
> Change `git --vesrion` to `git --version`

Thanks for pointing out.

**Comment by AkhileshThite** [comment]
@AkshayHere, [Fix](https://github.com/CuriousGrids/FirstTimers/commit/980db1f6d419990c79b2f02dee09a848d9add292)
